---
mongodb:
  image: mongo:4.2
  ports:
    - "27017"
  volumes:
    - "/data/db"

rabbitmq:
  image: rabbitmq:3.8
  ports:
    - "5672"

girder:
  build: .
  dockerfile: Dockerfile
  ports:
    - "8080:8080"
  links:
    - "mongodb:mongodb"
    - "rabbitmq:rabbitmq"
  environment:
    - "CELERY_BROKER_URL=amqp://rabbitmq:5672/"
    - "GIRDER_API=http://girder:8080/api/v1"
  command: --host 0.0.0.0 --database mongodb://mongodb:27017/girder

celery:
  build: .
  dockerfile: Dockerfile
  links:
    - "girder:girder"
    - "rabbitmq:rabbitmq"
  environment:
    - "CELERY_BROKER_URL=amqp://rabbitmq:5672/"
    - GIRDER_PORT=8080
    - C_FORCE_ROOT=1
  entrypoint: ["celery"]
  command: ["-A", "girder_nlisim.celery:app", "-l", "info", "worker"]
